#pragma once

enum SK_EVENT{
    SK_EVENT_KEY_PRESS = 0,
    SK_EVENT_KEY_LIFTED,
    SK_EVENT_MOUSE_PRESS,
    SK_EVENT_MOUSE_LIFTED,
    SK_EVENT_MOUSE_MOVE,
    SK_EVENT_WINDOW_RESIZE,
    SK_EVENT_PRERENDER,
};